# Basic Information
title: Fengpeng Li
position: PostDoc Research Fellow
affiliation: King Abdullah University of Science and Technology (KAUST)
affiliation_link: https://www.kaust.edu.sa/
location: Thuwal, Jedda City, Makkah Province, King Saudia Arabia
email: fengpeng.li@kaust.edu.sa
bio: trustworthy foundation models and agent, machine learning, GeoAI and AI security.
sidebar_note: I am especially interested in the theoretical foundations of trustworthy machine learning and AI, LLM, VLM and agent Robust Learning, trustworthy foundation models, and VLM LLM and agent for GeoAI.
research_areas:
  - trustworthy machine learning(LLM, VLM, Agent, and Diffusion Models)
  - Trustworthy AI (AIGC and DeepFake Detection)
  - GeoAI (Intelligent Method for Geosciences)
last_updated: 2026-05

# Search Engine Optimization (SEO)
keywords: Fengpeng Li, trustworthy machine learning and AI, GeoAI, KAUST
description: Fengpeng Li's academic homepage, featuring research interests, publications, awards, professional services, and teaching.

# Links
google_scholar: https://scholar.google.com/citations?user=DgaQZ4wAAAAJ&hl=zh-CN
cv_link: ./assets/files/CV_EN_Kemou_Li.pdf
github_link: https://github.com/kemoulee
linkedin: https://www.linkedin.com/in/kemou-li-211950268/
twitter: https://twitter.com/KemouLi99
instagram: https://www.instagram.com/kemoulee/
wechat: ./assets/img/wechat_qr.png

# Images
avatar: ./assets/img/photo2.jpg
avatar_back: ./assets/img/never_enough.jpg
favicon: ./assets/img/ghibli.png
favicon_dark: ./assets/img/ghibli.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Serif" # or "Sans Serif"

# Google Analytics ID
google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
